import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDatabase1758795982052 implements MigrationInterface {
    name = 'InitDatabase1758795982052'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "category_id" character varying, "title" character varying(255) NOT NULL, "subtitle" character varying(500), "content" text NOT NULL, "slug" character varying(255) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'draft', "view_count" integer NOT NULL DEFAULT '0', "like_count" integer NOT NULL DEFAULT '0', "comment_count" integer NOT NULL DEFAULT '0', "featured_image_url" character varying(500), "published_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_54ddf9075260407dcfdd7248577" UNIQUE ("slug"), CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54ddf9075260407dcfdd724857" ON "posts" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1313dd89c695e9fc8bd710ab5" ON "posts" ("published_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a69d9e2ae78ef7d100f8317ae0" ON "posts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c4f9a7bd77b489e711277ee598" ON "posts" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "user_name" character varying(30) NOT NULL, "phone_number" character varying(20), "role" character varying DEFAULT 'user', "provider" character varying, "social_id" character varying, "photo_url" character varying, "self_introduction" text, "age" integer, "location" character varying(100), "play_games" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c9b5b525a96ddc2c5647d7f7fa" ON "users" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_074a1f262efaca6aba16f7ed92" ON "users" ("user_name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" character varying NOT NULL, "user_id" character varying, "parent_id" character varying, "nickname" character varying(100), "password_hash" character varying(255), "content" text NOT NULL, "like_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "postId" uuid, "userId" uuid, "parentId" uuid, CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4c675567d2a58f0b07cef09c13" ON "comments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_259bf9825d9d198608d1b46b0b" ON "comments" ("post_id") `);
        await queryRunner.query(`CREATE TABLE "likes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "target_id" character varying NOT NULL, "target_type" character varying(20) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "postId" uuid, "commentId" uuid, CONSTRAINT "UQ_a8cf5c83dbdeb790e31170e91d5" UNIQUE ("user_id", "target_id", "target_type"), CONSTRAINT "PK_a9323de3f8bced7539a794b4a37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2c570911fd2daeb1ad6106a882" ON "likes" ("target_id", "target_type") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "slug" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_420d9f679d41281f282f5bc7d0" ON "categories" ("slug") `);
        await queryRunner.query(`CREATE TABLE "matches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying(20) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "ended_at" TIMESTAMP, CONSTRAINT "PK_8a22c7b2e0828988d51256117f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "match_users" ("match_id" uuid NOT NULL, "user_id" uuid NOT NULL, "joined_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ecefa0c54c1fdd56e65a521a62f" PRIMARY KEY ("match_id", "user_id"))`);
        await queryRunner.query(`CREATE TABLE "friendships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "friend_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_08af97d0be72942681757f07bc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_972c6bdd4bc18dda48b8aa4714" ON "friendships" ("friend_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c73eec6c7e7d5d1f2b3ce8b900" ON "friendships" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."friend_requests_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "friend_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requester_id" uuid NOT NULL, "recipient_id" uuid NOT NULL, "status" "public"."friend_requests_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3827ba86ce64ecb4b90c92eeea6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ce65f143c03c3071e41915ad2a" ON "friend_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_67ede80121abbc1e6eb2c39228" ON "friend_requests" ("recipient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a4e62994c6be786cd48cc5255" ON "friend_requests" ("requester_id") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_rooms_type_enum" AS ENUM('direct', 'group')`);
        await queryRunner.query(`CREATE TABLE "chat_rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "type" "public"."chat_rooms_type_enum" NOT NULL DEFAULT 'direct', "image_url" character varying(500), "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c69082bd83bffeb71b0f455bd59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38ad638ee4556faf91063ec5c4" ON "chat_rooms" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_98732db9b35fbb873abf4949f4" ON "chat_rooms" ("type") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_type_enum" AS ENUM('text', 'image', 'file', 'system')`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chat_room_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "type" "public"."chat_messages_type_enum" NOT NULL DEFAULT 'text', "content" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_52d89390506ed998a56a73c04c" ON "chat_messages" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e5fc47ecb06d4d7b84633b171" ON "chat_messages" ("sender_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3217ec6230770d4d2c826fc038" ON "chat_messages" ("chat_room_id") `);
        await queryRunner.query(`CREATE TABLE "tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "slug" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "UQ_b3aa10c29ea4e61a830362bd25a" UNIQUE ("slug"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3aa10c29ea4e61a830362bd25" ON "tags" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_room_members_role_enum" AS ENUM('owner', 'admin', 'member')`);
        await queryRunner.query(`CREATE TABLE "chat_room_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chat_room_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" "public"."chat_room_members_role_enum" NOT NULL DEFAULT 'member', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "unread_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_736e2c819bfb5e5ab96ce8b43c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f7d4d1d255b71027906de8357f" ON "chat_room_members" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_56628fb4cec79f2a02f34caf33" ON "chat_room_members" ("chat_room_id", "user_id") `);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_7e8d7c49f218ebb14314fdb3749" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_8770bd9030a3d13c5f79a7d2e81" FOREIGN KEY ("parentId") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_cfd8e81fac09d7339a32e57d904" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_e2fe567ad8d305fefc918d44f50" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_ec3c75d6522fc60e0ebaf58a6b7" FOREIGN KEY ("commentId") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_users" ADD CONSTRAINT "FK_24bd72804bb760e71224a7a0b1f" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_users" ADD CONSTRAINT "FK_c5df5df69ab824ab5791dc4d297" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendships" ADD CONSTRAINT "FK_c73eec6c7e7d5d1f2b3ce8b9002" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friendships" ADD CONSTRAINT "FK_972c6bdd4bc18dda48b8aa4714c" FOREIGN KEY ("friend_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friend_requests" ADD CONSTRAINT "FK_9a4e62994c6be786cd48cc52555" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "friend_requests" ADD CONSTRAINT "FK_67ede80121abbc1e6eb2c392288" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_rooms" ADD CONSTRAINT "FK_0ab506d5205f68799f59438ea6a" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_3217ec6230770d4d2c826fc0380" FOREIGN KEY ("chat_room_id") REFERENCES "chat_rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_9e5fc47ecb06d4d7b84633b1718" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_room_members" ADD CONSTRAINT "FK_cab77d6448846706ad9b0ba41c9" FOREIGN KEY ("chat_room_id") REFERENCES "chat_rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_room_members" ADD CONSTRAINT "FK_f7d4d1d255b71027906de8357f5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "chat_room_members" DROP CONSTRAINT "FK_f7d4d1d255b71027906de8357f5"`);
        await queryRunner.query(`ALTER TABLE "chat_room_members" DROP CONSTRAINT "FK_cab77d6448846706ad9b0ba41c9"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_9e5fc47ecb06d4d7b84633b1718"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_3217ec6230770d4d2c826fc0380"`);
        await queryRunner.query(`ALTER TABLE "chat_rooms" DROP CONSTRAINT "FK_0ab506d5205f68799f59438ea6a"`);
        await queryRunner.query(`ALTER TABLE "friend_requests" DROP CONSTRAINT "FK_67ede80121abbc1e6eb2c392288"`);
        await queryRunner.query(`ALTER TABLE "friend_requests" DROP CONSTRAINT "FK_9a4e62994c6be786cd48cc52555"`);
        await queryRunner.query(`ALTER TABLE "friendships" DROP CONSTRAINT "FK_972c6bdd4bc18dda48b8aa4714c"`);
        await queryRunner.query(`ALTER TABLE "friendships" DROP CONSTRAINT "FK_c73eec6c7e7d5d1f2b3ce8b9002"`);
        await queryRunner.query(`ALTER TABLE "match_users" DROP CONSTRAINT "FK_c5df5df69ab824ab5791dc4d297"`);
        await queryRunner.query(`ALTER TABLE "match_users" DROP CONSTRAINT "FK_24bd72804bb760e71224a7a0b1f"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_ec3c75d6522fc60e0ebaf58a6b7"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_e2fe567ad8d305fefc918d44f50"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_cfd8e81fac09d7339a32e57d904"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_8770bd9030a3d13c5f79a7d2e81"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_7e8d7c49f218ebb14314fdb3749"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56628fb4cec79f2a02f34caf33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7d4d1d255b71027906de8357f"`);
        await queryRunner.query(`DROP TABLE "chat_room_members"`);
        await queryRunner.query(`DROP TYPE "public"."chat_room_members_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3aa10c29ea4e61a830362bd25"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3217ec6230770d4d2c826fc038"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e5fc47ecb06d4d7b84633b171"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52d89390506ed998a56a73c04c"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98732db9b35fbb873abf4949f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38ad638ee4556faf91063ec5c4"`);
        await queryRunner.query(`DROP TABLE "chat_rooms"`);
        await queryRunner.query(`DROP TYPE "public"."chat_rooms_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a4e62994c6be786cd48cc5255"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67ede80121abbc1e6eb2c39228"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce65f143c03c3071e41915ad2a"`);
        await queryRunner.query(`DROP TABLE "friend_requests"`);
        await queryRunner.query(`DROP TYPE "public"."friend_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c73eec6c7e7d5d1f2b3ce8b900"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_972c6bdd4bc18dda48b8aa4714"`);
        await queryRunner.query(`DROP TABLE "friendships"`);
        await queryRunner.query(`DROP TABLE "match_users"`);
        await queryRunner.query(`DROP TABLE "matches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_420d9f679d41281f282f5bc7d0"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c570911fd2daeb1ad6106a882"`);
        await queryRunner.query(`DROP TABLE "likes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_259bf9825d9d198608d1b46b0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c675567d2a58f0b07cef09c13"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_074a1f262efaca6aba16f7ed92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9b5b525a96ddc2c5647d7f7fa"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4f9a7bd77b489e711277ee598"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a69d9e2ae78ef7d100f8317ae0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1313dd89c695e9fc8bd710ab5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54ddf9075260407dcfdd724857"`);
        await queryRunner.query(`DROP TABLE "posts"`);
    }

}
