export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div>{children}</div>
    </>
  );
}

// app/layout.tsx
//   ├── {children} (홈페이지)
//   └── {auth} (모달 슬롯)
//       └── app/@auth/layout.tsx
//           └── {children} (로그인 모달)
